
SET NAMES utf8mb4; SET time_zone = '+00:00';
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE,name VARCHAR(255),role ENUM('adjudicator','coordinator','chair','admin') NOT NULL DEFAULT 'adjudicator',password_hash VARCHAR(255) NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS drugs (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) UNIQUE,class VARCHAR(255),genes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS dictionary_event (id INT AUTO_INCREMENT PRIMARY KEY,diagnosis VARCHAR(512) NOT NULL,category VARCHAR(255),ctcae_term VARCHAR(255),admission_grade VARCHAR(64),icd10 VARCHAR(255),source ENUM('ICD','LAB') NOT NULL,caveat1 TEXT,outcome1 TEXT,caveat2 TEXT,outcome2 TEXT,caveat3 TEXT,outcome3 TEXT,lcat1 TEXT,lcat1_met1 TEXT,lcat1_met2 TEXT,lcat1_notmet TEXT,lcat2 TEXT,lcat2_met1 TEXT,lcat2_notmet TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uniq_event (diagnosis, IFNULL(icd10,''), source)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS drug_event_map (drug_id INT NOT NULL,dict_event_id INT NOT NULL,expected_flag TINYINT(1),PRIMARY KEY (drug_id, dict_event_id),FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE,FOREIGN KEY (dict_event_id) REFERENCES dictionary_event(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS patients (id INT AUTO_INCREMENT PRIMARY KEY,patient_code VARCHAR(64) UNIQUE,randomisation_date DATE NOT NULL,followup_end_date DATE NOT NULL,index_drug_id INT NOT NULL,created_by INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (index_drug_id) REFERENCES drugs(id),FOREIGN KEY (created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS patient_concomitant_drug (patient_id INT NOT NULL,drug_id INT NOT NULL,start_date DATE,stop_date DATE,PRIMARY KEY (patient_id, drug_id),FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS case_event (id INT AUTO_INCREMENT PRIMARY KEY,patient_id INT NOT NULL,dict_event_id INT NOT NULL,onset_datetime DATETIME,status ENUM('open','info_requested','submitted','consensus','closed') NOT NULL DEFAULT 'open',phenotype_override VARCHAR(512),is_lab_primary TINYINT(1),notes TEXT,created_by INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,FOREIGN KEY (dict_event_id) REFERENCES dictionary_event(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS evidence_icd (id INT AUTO_INCREMENT PRIMARY KEY,case_event_id INT NOT NULL,icd_code VARCHAR(64) NOT NULL,event_date DATE,encounter_id VARCHAR(64),details TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (case_event_id) REFERENCES case_event(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS evidence_lab (id INT AUTO_INCREMENT PRIMARY KEY,case_event_id INT NOT NULL,test VARCHAR(128) NOT NULL,value VARCHAR(64),units VARCHAR(32),ref_low VARCHAR(32),ref_high VARCHAR(32),threshold_met TINYINT(1),sample_datetime DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (case_event_id) REFERENCES case_event(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS evidence_note (id INT AUTO_INCREMENT PRIMARY KEY,case_event_id INT NOT NULL,note_type VARCHAR(64),filename VARCHAR(255),url VARCHAR(512),version INT,uploaded_by INT,uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (case_event_id) REFERENCES case_event(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS adjudication (id INT AUTO_INCREMENT PRIMARY KEY,case_event_id INT NOT NULL,adjudicator_id INT NOT NULL,framework ENUM('WHO-UMC','Naranjo') NOT NULL,responses JSON,auto_score INT,causality ENUM('Definite','Probable','Possible','Unrelated','Unable') NOT NULL,severity ENUM('Mild','Moderate','Severe') NOT NULL,expectedness ENUM('Expected','Unexpected','Not_Assessable') NOT NULL,index_attribution ENUM('Yes','No','Indeterminate') NOT NULL,suspected_concomitants JSON,rationale TEXT,missing_info JSON,submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uniq_adj (case_event_id, adjudicator_id),FOREIGN KEY (case_event_id) REFERENCES case_event(id) ON DELETE CASCADE,FOREIGN KEY (adjudicator_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS consensus (id INT AUTO_INCREMENT PRIMARY KEY,case_event_id INT NOT NULL UNIQUE,method ENUM('majority','meeting','arbitration') NOT NULL,decided_by INT,causality ENUM('Definite','Probable','Possible','Unrelated','Unable') NOT NULL,severity ENUM('Mild','Moderate','Severe') NOT NULL,expectedness ENUM('Expected','Unexpected','Not_Assessable') NOT NULL,suspected_drugs JSON,rationale TEXT,decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (case_event_id) REFERENCES case_event(id) ON DELETE CASCADE,FOREIGN KEY (decided_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (id BIGINT AUTO_INCREMENT PRIMARY KEY,entity_type VARCHAR(64) NOT NULL,entity_id BIGINT NOT NULL,field VARCHAR(128) NOT NULL,old_value TEXT,new_value TEXT,user_id INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
